name: RevolutionSMP
version: '${project.version}'
main: me.notpseudo.revolutionsmp.RevolutionSMP
api-version: 1.18
load: STARTUP
authors: [ NotPseudo ]
description: A custom plugin for the RevolutionSMP
depend: [ProtocolLib]
commands:
  potatobook:
    description: Applies a Potato Book to an item
    aliases:
      - hpb
      - pb
    usage: /potatobook [add | set] <number>
  recombobulate:
    description: Recombobulates an item
    aliases:
      - recomb
    usage: /recombobulate
  reforge:
    description: Applies a Reforge to an item
    aliases:
      - rf
    usage: /reforge <reforge>
  test:
    description: This is a test command!
    usage: /test
  profile:
    description: Views player stats
    aliases:
      - mystats
      - myinfo
    usage: /profile
  resetstats:
    description: Resets player stats
    aliases:
      - clearstats
      - newstats
      - wipe
    usage: /resetstats
  customenchant:
    description: Adds an enchantment to the item the player is holding
    usage: /customenchant <enchantment> <level>
  itemstats:
    description: Testing command to view the item stats on a held item
    aliases:
      - viewitemstats
      - iteminfo
    usage: /itemstats