name: RevolutionSMP
version: '${project.version}'
main: me.notpseudo.revolutionsmp.RevolutionSMP
api-version: 1.18
load: STARTUP
authors: [ NotPseudo ]
description: A custom plugin for the RevolutionSMP
depend: [ProtocolLib]
commands:
  potatobook:
    description: Applies a Potato Book to an item
    aliases:
      - hpb
      - pb
    usage: /potatobook [add | set] <number>
  recombobulate:
    description: Recombobulates an item
    aliases:
      - recomb
    usage: /recombobulate
  reforge:
    description: Applies a Reforge to an item
    aliases:
      - rf
    usage: /reforge <Reforge>
  giveitem:
    description: Gives custom items!
    aliases:
      - item
    usage: /giveitem <all | ItemID>
  profile:
    description: Views player stats
    aliases:
      - mystats
      - myinfo
    usage: /profile
  resetstats:
    description: Resets player stats
    aliases:
      - clearstats
      - newstats
      - wipe
    usage: /resetstats
  customenchant:
    description: Adds an enchantment to the item the player is holding
    usage: /customenchant <Enchantment> <level>
  itemstats:
    description: Testing command to view the item stats on a held item
    aliases:
      - viewitemstats
      - iteminfo
    usage: /itemstats
  addability:
    description: Adds ab ability to the item the player is holding
    usage: /addability <AbilityType>
    aliases:
      - ability
  editability:
    description: Edits abilities stored on the item the player is holding
    usage: /editability [mana | cooldown] <number>
  particletest:
    description: Used to test particle effects
    usage: /particletest
  customore:
    description: Used to spawn custom ore block for testing
    usage: /customore <CustomOreType>
    aliases:
      - createcustomore
  clearcustomores:
    description: Admin command to clear custom ore locations in the world
  spawncustom:
    description: Admin command to test spawning custom mobs
    usage: /spawncustom <CustomMobType>