package me.notpseudo.revolutionsmp.collections;

public enum CollectionType {

    WHEAT,
    POTATO,
    CARROT,
    PUMPKIN,
    MELON,
    CACTUS,
    NETHER_WART,
    COCOA,
    MUSHROOM,
    SUGARCANE,
    BEETROOT,
    SWEET_BERRY,
    FUNGUS,
    GLOW_BERRY,
    DEAD_BUSH,
    FEATHER,
    LEATHER,
    MUTTON,
    CHICKEN,
    PORK,
    RABBIT,
    COBBLESTONE,
    GRAVEL,
    SAND,
    OBSIDIAN,
    DEEPSLATE,
    ICE,
    COAL,
    DIAMOND,
    EMERALD,
    GOLD,
    IRON,
    COPPER,
    LAPIS,
    REDSTONE,
    QUARTZ,
    GLOWSTONE,
    NETHERITE,
    MITHRIL,
    GEMSTONE,
    BLAZE_ROD,
    BONE,
    ENDER_PEARL,
    GHAST_TEAR,
    GUNPOWDER,
    MAGMA_CREAM,
    ROTTEN_FLESH,
    SLIMEBALL,
    SPIDER_EYE,
    STRING,
    PHANTOM_MEMBRANE,
    ACACIA_WOOD,
    BITCH_WOOD,
    DARK_OAK_WOOD,
    JUNGLE_WOOD,
    OAK_WOOD,
    SPRUCE_WOOD,
    CRIMSON_WOOD,
    WARPED_WOOD,
    CLAY,
    TROPICAL_FISH,
    INK_SAC,
    LILY_PAD,
    PRISMARINE,
    PUFFERFISH,
    COD,
    SALMON,
    SPONGE,
    SEAWEED;

    public CollectionCategory getCategory() {
        return null;
    }

}